name: Fetch blog posts and send draft

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 19 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Create env file
      run: |
        touch .env
        echo BUTTONDOWN_EMAIL_TOKEN=${{ secrets.BUTTONDOWN_EMAIL_TOKEN }} >> .env
        echo BLOG_NAME=${{ secrets.BLOG_NAME }} >> .env
        echo EMAIL=${{ secrets.EMAIL }} >> .env
        echo JSON_ENDPOINT=${{ secrets.JSON_ENDPOINT }} >> .env
        echo POST_LIMIT=${{ secrets.POST_LIMIT }} >> .env
        echo TWITTER_HANDLE=${{ secrets.TWITTER_HANDLE }} >> .env
    - name: Fetch JSON
      run: |-
        npm run fetch
    - name: Commit, push and send draft if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Send to buttondown.email" -a && npm run send || echo "No changes"
        git push
    - name: Delete env file
      run: |
        rm .env
