name: Send email

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Create env file
      run: |
        touch .env
        echo BUTTONDOWN_EMAIL_TOKEN=${{ secrets.BUTTONDOWN_EMAIL_TOKEN }} >> .env
    - name: Send Email
      run: |-
        npm start
    - name: Delete env file
      run: |
        rm .env
